### ISSUE TITLE
Some issues to be fixed within the README

### ISSUE THREAD

**Issue by cmoulliard** [aureamunoz/hello-world-fwless#1]
### Issue

The README file of the following [k8s branch](https://github.com/aureamunoz/hello-world-fwless/tree/dekorate4k8s) contains some issues: 
- The client to be used should  be `kubectl` and not `oc`
- The command to expose a route/service on kubernetes cannot rely on `oc expose service hello-world-fwless` as this command is specific to the openshift platform. As kubernetes uses ingress, then an ingress route must be created using either dekorate or a yml file

**Comment by aureamunoz** [comment]
Yes, The readme contains rests of copy/paste. This is going to be fixed with the fix of https://github.com/aureamunoz/hello-world-fwless/issues/2.
